### ISSUE TITLE
Reading record_date

### ISSUE THREAD

**Issue by KingRyuShin** [Artnod-FiveM-Mods/esx_races#3]
The races work fine, but when it's time to go back on the marker and check our time we get this error : 

https://i.imgur.com/s0khepW.png

**Comment by artnod78** [comment]
I changed `datetime` type to `integer` type in db. And I replaced `NOW()` to `os.time()` in server script.

**Comment by KingRyuShin** [comment]
> I changed `datetime` type to `integer` type in db. And I replaced `NOW()` to `os.time()` in server script.

just to let you knew that with the new mysql-async version, the version before your update is working fine.
